name: travelminapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  chewie: ^0.9.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/fishing.jpg
   - assets/kathmandu.jpg
   - assets/mountain.jpg
   - assets/profil.jpeg
   - assets/pic_4.jpg
   - assets/virtual_coach.jpeg
   - assets/esport.png
   - assets/etricks.jpg
   - assets/etricks_2.jpg
   - assets/coach.png
   - videos/coach.mp4
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Opensans
      fonts:
        - asset: assets/OpenSans-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

